language: java
jdk: oraclejdk11
sudo: false # faster builds

script:
  - chmod +x gradlew
  - ./gradlew projects tasks clean build jacocoTestReport --no-daemon --refresh-dependencies

after_success:
  - bash <(curl -s https://codecov.io/bash)
